xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

$HOME/.screenlayout/layout.sh && $HOME/.fehbg

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

export FZF_DEFAULT_COMMAND='find . -name "*" -type f'

exec dwm
