# go
export GOPATH=$HOME/Workspace/gopath
export GO111MODULE=on
export GOPROXY=https://goproxy.cn

case ":$PATH:" in
    *:"$GOPATH/bin":*)
        ;;
    *)
        PATH="${PATH:+$PATH:}$GOPATH/bin"
esac

export PATH
