autoload -U compinit promptinit
compinit
zstyle ':completion:*' menu select
setopt completealiases
setopt HIST_IGNORE_DUPS
promptinit

prompt walters

alias ls='ls --color=tty'
alias ll='ls -l --color=tty'
alias la='ls -A --color=tty'
alias lla='ls -Al --color=tty'
alias s='neofetch'
alias ra='ranger'
alias lzg='lazygit'
alias pacman='sudo pacman'

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
